### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by stevenguh** [VSpaceCode/VSpaceCode#49]
This is an issue to track the work up to `v0.5.0`

🏃 - In Progress

## v0.4.0
- [x] Basic transient menu
- [x] Argument passing in command calling which enables vim command/key calling
- [x] Change the bindings so it's more in line with spacemacs bindings (https://github.com/stevenguh/spacecode/issues/8)
- [x] Add one time notification for when the extension is updated

## v0.4.x
- Any bug fixes
- Missing key bindings update

## v0.5.0
- [x] Break off the core menu structure to [`vscode-which-code`](https://github.com/VSpaceCode/vscode-which-key) (@stevenguh)
- [x] Drop support for non-Vim users and redirect them to `vscode-which-code`
- [x] Support `y` menu in magit (@stevenguh)
- [x] Figure out the installation
- [x] Experiment with [extension pack](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup)
- [x] Drop GitLens bindings in git menu in favor of edamagit
- [x] Add `<spc> j` and easymotion settings on install

## Miscellaneous/Bug
- [x] Use webpack to reduce size
- [x] Choose a optimal ts transpiring target for the vscode version targeted
- [x] Fix the vim check when the extension is install in VSCode Remote
- [x] Create a contribution guide (#48)

**Comment by MarcoIeni** [comment]
> Experiment with extension pack

I'll provide some context about this point.
It means that this repo will become an extension pack that bundles together plugins that brings the spacemacs experience to vs code. Among these plugins there will be vscode-which-code.

`vscode-which-code` (which by the way I will name `vscode-which-key` in order to be more explicit :stuck_out_tongue: ) plugin will be extracted by this plugin, in order to customize its default key bindings. This repository will use the `vscode-which-code` plugin to define spacemacs key bindings of course.

**Comment by MarcoIeni** [comment]
Anyway for issues like this in the future we could explore the [milestone](https://github.com/VSpaceCode/VSpaceCode/milestones) github feature. I have never used it but the description seems to fit what we are doing here.
There are also projects, but again, never used those.

**Comment by stevenguh** [comment]
I have never used milestone before. I just looked it up, it seems good. I think breaking things into tasks and put them in milestone would be cool to see what we need to release v0.5.0 for example. However, I am a little worried that it might turn into a managerial time sink.

I used projects before, but they are kind similar in what they do. I guess milestone requires all task be created in issue, and project has a bit more freedom.

I would favor a lightweight roadmap issue now until more people are contributing so it requires that level of project management.

**Comment by stevenguh** [comment]
`v0.4.0` is ready and will be deployed on Monday morning Seattle time. The reason is to give a few days for people to move over from `spacecode` to here 😊

**Comment by StreakyCobra** [comment]
> v0.4.0 is ready and will be deployed on Monday morning Seattle time. The reason is to give a few days for people to move over from spacecode to here blush

Impressive work :clap: I'm looking forward to try it :)

**Comment by stevenguh** [comment]
> I would favor a lightweight roadmap issue now until more people are contributing so it requires that level of project management.

I think issues are piling up, and I triaged some of them with labels and I think we should experiment with the milestone. I created a `v0.5.0` milestone, and am thinking the milestone is currently used to include issue that are `v0.5.0` candidate, and not necessary to create issues for each features we are going to work on as we have the roadmap to track the core functions. (I can also see the up side of creating an issue for each features, but time...⏳)

**Comment by stevenguh** [comment]
`v0.5.0` is feature complete and will release some time early next week
